version: '3.8'

services:
  invoicegenerator-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      CONFIG_KEY: ${CONFIG_KEY}
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ./token_store:/app/token_store