version: '3.8'

services:
  invoicegenerator-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      # CONFIG_KEY: ${CONFIG_KEY}                   # Pass secret at runtime via env var
      CONFIG_KEY: your_secret_key
      ASPNETCORE_ENVIRONMENT: Development         # Match your config
      ENCRYPTED_JSON_CONFIG: /app/Config/secure.Development.appsettings.json
    volumes:
      - ./token_store:/app/token_store             # Mount token_store to persist OAuth tokens
