version: '3.8'

services:
  invoicegenerator-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      CONFIG_KEY: your_decryption_key
      ASPNETCORE_ENVIRONMENT: Development